---
- name: "check mandatory variables"
  assert:
    that:
      - systemd_service.name is defined
  tags: ['check_vars']

- name: creating systemd service
  include_tasks: common-service.yml
  when: systemd_service.podman is not defined or systemd_service.podman.image is not defined

- name: creating systemd podman service
  include_tasks: podman-service.yml
  when: systemd_service.podman is defined and systemd_service.podman.image is defined

- name: "Enabling and starting {{ systemd_service.name }}"
  systemd:
    name: "{{ systemd_service.name }}"
    daemon_reload: true
    state: "{{ systemd_service.state | default(systemd_service_defaults.state) }}"
    enabled: "{{ systemd_service.enabled | default(omit) }}"
  become: true

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
